### ISSUE TITLE
Add csound ipython info to the “Create” page

### ISSUE THREAD

**Issue by ghost** [csound/csound.github.io#29]

**Comment by kunstmusik** [comment]
@mantaraya36 Could you maybe take a look at this?  (We are currently working in the new-site branch)

**Comment by kunstmusik** [comment]
@fggp : Francois, @berntisak and I are looking at the website issues and were wondering about this.  I *think* this issue is about ipython notebook, but I wasn't sure. I saw that there's newer work now based on jupyter notebook (https://github.com/csound/csound/wiki/csoundmagics). Could you maybe advise on what might be good to add to the csound.com site?

**Comment by kunstmusik** [comment]
@fggp Thanks for that. We can work this into the site revisions. :)

**Comment by joachimheintz** [comment]
i think this is more or less done, so i am closing.
